// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *ApiToken) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Catalog) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CatalogItem) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CatalogMedia) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CatalogvAppTemplate) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClonedvApp) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Edgegateway) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EdgegatewaySettings) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EdgegatewayVPN) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ExternalNetwork) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ExternalNetworkV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GlobalRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IndependentDisk) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *InsertedMedia) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IpSpace) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IpSpaceCustomQuota) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IpSpaceIpAllocation) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IpSpaceUplink) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LbAppProfile) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LbAppRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LbServerPool) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LbServiceMonitor) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LbVirtualServer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NetworkDirect) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NetworkIsolated) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NetworkIsolatedV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NetworkRouted) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NetworkRoutedV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtAlbCloud) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtAlbController) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtAlbEdgegatewayServiceEngineGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtAlbPool) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtAlbServiceEngineGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtAlbSettings) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtAlbVirtualService) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtAppPortProfile) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtDistributedFirewall) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtDistributedFirewallRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtDynamicSecurityGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtEdgeGateway) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtEdgegatewayBgpConfiguration) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtEdgeGatewayBgpIpPrefixList) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtEdgeGatewayBgpNeighbor) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtEdgeGatewayDhcpV6) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtEdgeGatewayRateLimit) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtEdgeGatewayStaticRoute) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtFirewall) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtIpsecVpnTunnel) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtIpSet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtNatRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtNetworkDhcp) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtNetworkDhcpBinding) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtNetworkImported) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtRouteAdvertisement) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxtSecurityGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxvDhcpRelay) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxvDistributedFirewall) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxvDnat) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxvFirewallRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxvIpSet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NsxvSnat) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Org) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrgGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrgLdap) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrgSaml) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrgUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrgVdc) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrgVdcAccessControl) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProviderVdc) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Rde) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RdeInterface) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RdeInterfaceBehavior) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RdeType) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RdeTypeBehavior) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RdeTypeBehaviorAcl) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RightsBundle) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Role) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SecurityTag) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServiceAccount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SubscribedCatalog) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UiPlugin) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VApp) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VAppAccessControl) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VAppFirewallRules) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VAppNatRules) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VAppNetwork) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VAppOrgNetwork) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VAppStaticRouting) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VAppVm) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VdcGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Vm) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VmAffinityRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VmInternalDisk) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VmPlacementPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VmSizingPolicy) Hub() {}
