// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type InsertedMediaInitParameters struct {

	// The name of the catalog where to find media file
	// catalog name where to find media file
	Catalog *string `json:"catalog,omitempty" tf:"catalog,omitempty"`

	// Allows to pass answer to question in vCD
	// "The guest operating system has locked the CD-ROM door and is probably using the CD-ROM.
	// Disconnect anyway (and override the lock)?"
	// when ejecting from a VM which is powered on. True means "Yes" as answer to question. Default is true
	// When ejecting answers automatically to question yes
	EjectForce *bool `json:"ejectForce,omitempty" tf:"eject_force,omitempty"`

	// Media file name in catalog which will be inserted to VM
	// media name to use
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organisations
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// - The name of VM to be used to insert media file
	// VM in vApp in which media will be inserted or ejected
	VMName *string `json:"vmName,omitempty" tf:"vm_name,omitempty"`

	// - The name of vApp to find
	// vApp to use
	VappName *string `json:"vappName,omitempty" tf:"vapp_name,omitempty"`

	// The name of VDC to use, optional if defined at provider level
	// The name of VDC to use, optional if defined at provider level
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type InsertedMediaObservation struct {

	// The name of the catalog where to find media file
	// catalog name where to find media file
	Catalog *string `json:"catalog,omitempty" tf:"catalog,omitempty"`

	// Allows to pass answer to question in vCD
	// "The guest operating system has locked the CD-ROM door and is probably using the CD-ROM.
	// Disconnect anyway (and override the lock)?"
	// when ejecting from a VM which is powered on. True means "Yes" as answer to question. Default is true
	// When ejecting answers automatically to question yes
	EjectForce *bool `json:"ejectForce,omitempty" tf:"eject_force,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Media file name in catalog which will be inserted to VM
	// media name to use
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organisations
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// - The name of VM to be used to insert media file
	// VM in vApp in which media will be inserted or ejected
	VMName *string `json:"vmName,omitempty" tf:"vm_name,omitempty"`

	// - The name of vApp to find
	// vApp to use
	VappName *string `json:"vappName,omitempty" tf:"vapp_name,omitempty"`

	// The name of VDC to use, optional if defined at provider level
	// The name of VDC to use, optional if defined at provider level
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type InsertedMediaParameters struct {

	// The name of the catalog where to find media file
	// catalog name where to find media file
	// +kubebuilder:validation:Optional
	Catalog *string `json:"catalog,omitempty" tf:"catalog,omitempty"`

	// Allows to pass answer to question in vCD
	// "The guest operating system has locked the CD-ROM door and is probably using the CD-ROM.
	// Disconnect anyway (and override the lock)?"
	// when ejecting from a VM which is powered on. True means "Yes" as answer to question. Default is true
	// When ejecting answers automatically to question yes
	// +kubebuilder:validation:Optional
	EjectForce *bool `json:"ejectForce,omitempty" tf:"eject_force,omitempty"`

	// Media file name in catalog which will be inserted to VM
	// media name to use
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organisations
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// - The name of VM to be used to insert media file
	// VM in vApp in which media will be inserted or ejected
	// +kubebuilder:validation:Optional
	VMName *string `json:"vmName,omitempty" tf:"vm_name,omitempty"`

	// - The name of vApp to find
	// vApp to use
	// +kubebuilder:validation:Optional
	VappName *string `json:"vappName,omitempty" tf:"vapp_name,omitempty"`

	// The name of VDC to use, optional if defined at provider level
	// The name of VDC to use, optional if defined at provider level
	// +kubebuilder:validation:Optional
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

// InsertedMediaSpec defines the desired state of InsertedMedia
type InsertedMediaSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     InsertedMediaParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InsertedMediaInitParameters `json:"initProvider,omitempty"`
}

// InsertedMediaStatus defines the observed state of InsertedMedia.
type InsertedMediaStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InsertedMediaObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// InsertedMedia is the Schema for the InsertedMedias API. Provides a VMware Cloud Director resource for inserting or ejecting media (ISO) file for the VM. Create this resource for inserting the media, and destroy it for ejecting.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type InsertedMedia struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.catalog) || (has(self.initProvider) && has(self.initProvider.catalog))",message="spec.forProvider.catalog is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vappName) || (has(self.initProvider) && has(self.initProvider.vappName))",message="spec.forProvider.vappName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vmName) || (has(self.initProvider) && has(self.initProvider.vmName))",message="spec.forProvider.vmName is a required parameter"
	Spec   InsertedMediaSpec   `json:"spec"`
	Status InsertedMediaStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InsertedMediaList contains a list of InsertedMedias
type InsertedMediaList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InsertedMedia `json:"items"`
}

// Repository type metadata.
var (
	InsertedMedia_Kind             = "InsertedMedia"
	InsertedMedia_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: InsertedMedia_Kind}.String()
	InsertedMedia_KindAPIVersion   = InsertedMedia_Kind + "." + CRDGroupVersion.String()
	InsertedMedia_GroupVersionKind = CRDGroupVersion.WithKind(InsertedMedia_Kind)
)

func init() {
	SchemeBuilder.Register(&InsertedMedia{}, &InsertedMediaList{})
}
