// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type NetworkIsolatedV2InitParameters struct {

	// A FQDN for the virtual machines on this network
	// DNS suffix
	DNSSuffix *string `json:"dnsSuffix,omitempty" tf:"dns_suffix,omitempty"`

	// An optional description of the network
	// Network description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// First DNS server to use.
	// DNS server 1
	Dns1 *string `json:"dns1,omitempty" tf:"dns1,omitempty"`

	// Second DNS server to use.
	// DNS server 1
	Dns2 *string `json:"dns2,omitempty" tf:"dns2,omitempty"`

	// Enables Dual-Stack mode so that one can configure one
	// IPv4 and one IPv6 networks. Note In such case IPv4 addresses must be used in gateway,
	// prefix_length and static_ip_pool while IPv6 addresses in secondary_gateway,
	// secondary_prefix_length and secondary_static_ip_pool fields.
	// Boolean value if Dual-Stack mode should be enabled (default `false`)
	DualStackEnabled *bool `json:"dualStackEnabled,omitempty" tf:"dual_stack_enabled,omitempty"`

	// The gateway for this network (e.g. 192.168.1.1, 2002:0:0:1234:abcd:ffff:c0a7:121)
	// Gateway IP address
	Gateway *string `json:"gateway,omitempty" tf:"gateway,omitempty"`

	// Set to true if network should allow guest VLAN tagging.
	// Default false.
	// True if network allows guest VLAN tagging
	GuestVlanAllowed *bool `json:"guestVlanAllowed,omitempty" tf:"guest_vlan_allowed,omitempty"`

	// NSX-V only. Defines if this network is shared between multiple VDCs
	// in the Org.  Defaults to false.
	// NSX-V only - share this network with other VDCs in this organization. Default - false
	IsShared *bool `json:"isShared,omitempty" tf:"is_shared,omitempty"`

	// (Deprecated; v3.6+) Use metadata_entry instead. Key value map of metadata to assign to this network. Not supported if the network belongs to a VDC Group.
	// Key value map of metadata to assign to this network. Key and value can be any string
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// A set of metadata entries to assign. See Metadata section for details.
	// Metadata entries for the given Network
	MetadataEntry []NetworkIsolatedV2MetadataEntryInitParameters `json:"metadataEntry,omitempty" tf:"metadata_entry,omitempty"`

	// A unique name for the network
	// Network name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful
	// when connected as sysadmin working across different organisations
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// VDC or VDC Group ID. Always takes precedence over vdc fields (in resource
	// and inherited from provider configuration)
	// ID of VDC or VDC Group
	OwnerID *string `json:"ownerId,omitempty" tf:"owner_id,omitempty"`

	// The prefix length for the new network (e.g. 24 for netmask 255.255.255.0).
	// Network prefix
	PrefixLength *float64 `json:"prefixLength,omitempty" tf:"prefix_length,omitempty"`

	// IPv6 gateway when Dual-Stack mode is enabled
	// Secondary gateway (can only be IPv6 and requires enabled Dual Stack mode)
	SecondaryGateway *string `json:"secondaryGateway,omitempty" tf:"secondary_gateway,omitempty"`

	// IPv6 prefix length when Dual-Stack mode is
	// enabled
	// Secondary prefix (can only be IPv6 and requires enabled Dual Stack mode)
	SecondaryPrefixLength *string `json:"secondaryPrefixLength,omitempty" tf:"secondary_prefix_length,omitempty"`

	// One or more IPv6 static
	// pools when Dual-Stack mode is enabled
	// Secondary IP ranges used for static pool allocation in the network
	SecondaryStaticIPPool []SecondaryStaticIPPoolInitParameters `json:"secondaryStaticIpPool,omitempty" tf:"secondary_static_ip_pool,omitempty"`

	// A range of IPs permitted to be used as static IPs for
	// virtual machines; see IP Pools below for details.
	// IP ranges used for static pool allocation in the network
	StaticIPPool []NetworkIsolatedV2StaticIPPoolInitParameters `json:"staticIpPool,omitempty" tf:"static_ip_pool,omitempty"`

	// (Deprecated; Optional) The name of VDC to use. Deprecated  in favor of new field
	// owner_id which supports VDC and VDC Group IDs.
	// The name of VDC to use, optional if defined at provider level
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type NetworkIsolatedV2MetadataEntryInitParameters struct {

	// Domain for this metadata entry. true if it belongs to SYSTEM, false if it belongs to GENERAL.
	// Domain for this metadata entry. true, if it belongs to SYSTEM. false, if it belongs to GENERAL
	IsSystem *bool `json:"isSystem,omitempty" tf:"is_system,omitempty"`

	// Key of this metadata entry.
	// Key of this metadata entry. Required if the metadata entry is not empty
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Type of this metadata entry. One of: MetadataStringValue, MetadataNumberValue, MetadataDateTimeValue, MetadataBooleanValue.
	// Type of this metadata entry. One of: 'MetadataStringValue', 'MetadataNumberValue', 'MetadataBooleanValue', 'MetadataDateTimeValue'
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// User access level for this metadata entry. One of: PRIVATE (hidden), READONLY (read only), READWRITE (read/write).
	// User access level for this metadata entry. One of: 'READWRITE', 'READONLY', 'PRIVATE'
	UserAccess *string `json:"userAccess,omitempty" tf:"user_access,omitempty"`

	// Value of this metadata entry.
	// Value of this metadata entry. Required if the metadata entry is not empty
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type NetworkIsolatedV2MetadataEntryObservation struct {

	// Domain for this metadata entry. true if it belongs to SYSTEM, false if it belongs to GENERAL.
	// Domain for this metadata entry. true, if it belongs to SYSTEM. false, if it belongs to GENERAL
	IsSystem *bool `json:"isSystem,omitempty" tf:"is_system,omitempty"`

	// Key of this metadata entry.
	// Key of this metadata entry. Required if the metadata entry is not empty
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Type of this metadata entry. One of: MetadataStringValue, MetadataNumberValue, MetadataDateTimeValue, MetadataBooleanValue.
	// Type of this metadata entry. One of: 'MetadataStringValue', 'MetadataNumberValue', 'MetadataBooleanValue', 'MetadataDateTimeValue'
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// User access level for this metadata entry. One of: PRIVATE (hidden), READONLY (read only), READWRITE (read/write).
	// User access level for this metadata entry. One of: 'READWRITE', 'READONLY', 'PRIVATE'
	UserAccess *string `json:"userAccess,omitempty" tf:"user_access,omitempty"`

	// Value of this metadata entry.
	// Value of this metadata entry. Required if the metadata entry is not empty
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type NetworkIsolatedV2MetadataEntryParameters struct {

	// Domain for this metadata entry. true if it belongs to SYSTEM, false if it belongs to GENERAL.
	// Domain for this metadata entry. true, if it belongs to SYSTEM. false, if it belongs to GENERAL
	// +kubebuilder:validation:Optional
	IsSystem *bool `json:"isSystem,omitempty" tf:"is_system,omitempty"`

	// Key of this metadata entry.
	// Key of this metadata entry. Required if the metadata entry is not empty
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Type of this metadata entry. One of: MetadataStringValue, MetadataNumberValue, MetadataDateTimeValue, MetadataBooleanValue.
	// Type of this metadata entry. One of: 'MetadataStringValue', 'MetadataNumberValue', 'MetadataBooleanValue', 'MetadataDateTimeValue'
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// User access level for this metadata entry. One of: PRIVATE (hidden), READONLY (read only), READWRITE (read/write).
	// User access level for this metadata entry. One of: 'READWRITE', 'READONLY', 'PRIVATE'
	// +kubebuilder:validation:Optional
	UserAccess *string `json:"userAccess,omitempty" tf:"user_access,omitempty"`

	// Value of this metadata entry.
	// Value of this metadata entry. Required if the metadata entry is not empty
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type NetworkIsolatedV2Observation struct {

	// A FQDN for the virtual machines on this network
	// DNS suffix
	DNSSuffix *string `json:"dnsSuffix,omitempty" tf:"dns_suffix,omitempty"`

	// An optional description of the network
	// Network description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// First DNS server to use.
	// DNS server 1
	Dns1 *string `json:"dns1,omitempty" tf:"dns1,omitempty"`

	// Second DNS server to use.
	// DNS server 1
	Dns2 *string `json:"dns2,omitempty" tf:"dns2,omitempty"`

	// Enables Dual-Stack mode so that one can configure one
	// IPv4 and one IPv6 networks. Note In such case IPv4 addresses must be used in gateway,
	// prefix_length and static_ip_pool while IPv6 addresses in secondary_gateway,
	// secondary_prefix_length and secondary_static_ip_pool fields.
	// Boolean value if Dual-Stack mode should be enabled (default `false`)
	DualStackEnabled *bool `json:"dualStackEnabled,omitempty" tf:"dual_stack_enabled,omitempty"`

	// The gateway for this network (e.g. 192.168.1.1, 2002:0:0:1234:abcd:ffff:c0a7:121)
	// Gateway IP address
	Gateway *string `json:"gateway,omitempty" tf:"gateway,omitempty"`

	// Set to true if network should allow guest VLAN tagging.
	// Default false.
	// True if network allows guest VLAN tagging
	GuestVlanAllowed *bool `json:"guestVlanAllowed,omitempty" tf:"guest_vlan_allowed,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// NSX-V only. Defines if this network is shared between multiple VDCs
	// in the Org.  Defaults to false.
	// NSX-V only - share this network with other VDCs in this organization. Default - false
	IsShared *bool `json:"isShared,omitempty" tf:"is_shared,omitempty"`

	// (Deprecated; v3.6+) Use metadata_entry instead. Key value map of metadata to assign to this network. Not supported if the network belongs to a VDC Group.
	// Key value map of metadata to assign to this network. Key and value can be any string
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// A set of metadata entries to assign. See Metadata section for details.
	// Metadata entries for the given Network
	MetadataEntry []NetworkIsolatedV2MetadataEntryObservation `json:"metadataEntry,omitempty" tf:"metadata_entry,omitempty"`

	// A unique name for the network
	// Network name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful
	// when connected as sysadmin working across different organisations
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// VDC or VDC Group ID. Always takes precedence over vdc fields (in resource
	// and inherited from provider configuration)
	// ID of VDC or VDC Group
	OwnerID *string `json:"ownerId,omitempty" tf:"owner_id,omitempty"`

	// The prefix length for the new network (e.g. 24 for netmask 255.255.255.0).
	// Network prefix
	PrefixLength *float64 `json:"prefixLength,omitempty" tf:"prefix_length,omitempty"`

	// IPv6 gateway when Dual-Stack mode is enabled
	// Secondary gateway (can only be IPv6 and requires enabled Dual Stack mode)
	SecondaryGateway *string `json:"secondaryGateway,omitempty" tf:"secondary_gateway,omitempty"`

	// IPv6 prefix length when Dual-Stack mode is
	// enabled
	// Secondary prefix (can only be IPv6 and requires enabled Dual Stack mode)
	SecondaryPrefixLength *string `json:"secondaryPrefixLength,omitempty" tf:"secondary_prefix_length,omitempty"`

	// One or more IPv6 static
	// pools when Dual-Stack mode is enabled
	// Secondary IP ranges used for static pool allocation in the network
	SecondaryStaticIPPool []SecondaryStaticIPPoolObservation `json:"secondaryStaticIpPool,omitempty" tf:"secondary_static_ip_pool,omitempty"`

	// A range of IPs permitted to be used as static IPs for
	// virtual machines; see IP Pools below for details.
	// IP ranges used for static pool allocation in the network
	StaticIPPool []NetworkIsolatedV2StaticIPPoolObservation `json:"staticIpPool,omitempty" tf:"static_ip_pool,omitempty"`

	// (Deprecated; Optional) The name of VDC to use. Deprecated  in favor of new field
	// owner_id which supports VDC and VDC Group IDs.
	// The name of VDC to use, optional if defined at provider level
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type NetworkIsolatedV2Parameters struct {

	// A FQDN for the virtual machines on this network
	// DNS suffix
	// +kubebuilder:validation:Optional
	DNSSuffix *string `json:"dnsSuffix,omitempty" tf:"dns_suffix,omitempty"`

	// An optional description of the network
	// Network description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// First DNS server to use.
	// DNS server 1
	// +kubebuilder:validation:Optional
	Dns1 *string `json:"dns1,omitempty" tf:"dns1,omitempty"`

	// Second DNS server to use.
	// DNS server 1
	// +kubebuilder:validation:Optional
	Dns2 *string `json:"dns2,omitempty" tf:"dns2,omitempty"`

	// Enables Dual-Stack mode so that one can configure one
	// IPv4 and one IPv6 networks. Note In such case IPv4 addresses must be used in gateway,
	// prefix_length and static_ip_pool while IPv6 addresses in secondary_gateway,
	// secondary_prefix_length and secondary_static_ip_pool fields.
	// Boolean value if Dual-Stack mode should be enabled (default `false`)
	// +kubebuilder:validation:Optional
	DualStackEnabled *bool `json:"dualStackEnabled,omitempty" tf:"dual_stack_enabled,omitempty"`

	// The gateway for this network (e.g. 192.168.1.1, 2002:0:0:1234:abcd:ffff:c0a7:121)
	// Gateway IP address
	// +kubebuilder:validation:Optional
	Gateway *string `json:"gateway,omitempty" tf:"gateway,omitempty"`

	// Set to true if network should allow guest VLAN tagging.
	// Default false.
	// True if network allows guest VLAN tagging
	// +kubebuilder:validation:Optional
	GuestVlanAllowed *bool `json:"guestVlanAllowed,omitempty" tf:"guest_vlan_allowed,omitempty"`

	// NSX-V only. Defines if this network is shared between multiple VDCs
	// in the Org.  Defaults to false.
	// NSX-V only - share this network with other VDCs in this organization. Default - false
	// +kubebuilder:validation:Optional
	IsShared *bool `json:"isShared,omitempty" tf:"is_shared,omitempty"`

	// (Deprecated; v3.6+) Use metadata_entry instead. Key value map of metadata to assign to this network. Not supported if the network belongs to a VDC Group.
	// Key value map of metadata to assign to this network. Key and value can be any string
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// A set of metadata entries to assign. See Metadata section for details.
	// Metadata entries for the given Network
	// +kubebuilder:validation:Optional
	MetadataEntry []NetworkIsolatedV2MetadataEntryParameters `json:"metadataEntry,omitempty" tf:"metadata_entry,omitempty"`

	// A unique name for the network
	// Network name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful
	// when connected as sysadmin working across different organisations
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// VDC or VDC Group ID. Always takes precedence over vdc fields (in resource
	// and inherited from provider configuration)
	// ID of VDC or VDC Group
	// +kubebuilder:validation:Optional
	OwnerID *string `json:"ownerId,omitempty" tf:"owner_id,omitempty"`

	// The prefix length for the new network (e.g. 24 for netmask 255.255.255.0).
	// Network prefix
	// +kubebuilder:validation:Optional
	PrefixLength *float64 `json:"prefixLength,omitempty" tf:"prefix_length,omitempty"`

	// IPv6 gateway when Dual-Stack mode is enabled
	// Secondary gateway (can only be IPv6 and requires enabled Dual Stack mode)
	// +kubebuilder:validation:Optional
	SecondaryGateway *string `json:"secondaryGateway,omitempty" tf:"secondary_gateway,omitempty"`

	// IPv6 prefix length when Dual-Stack mode is
	// enabled
	// Secondary prefix (can only be IPv6 and requires enabled Dual Stack mode)
	// +kubebuilder:validation:Optional
	SecondaryPrefixLength *string `json:"secondaryPrefixLength,omitempty" tf:"secondary_prefix_length,omitempty"`

	// One or more IPv6 static
	// pools when Dual-Stack mode is enabled
	// Secondary IP ranges used for static pool allocation in the network
	// +kubebuilder:validation:Optional
	SecondaryStaticIPPool []SecondaryStaticIPPoolParameters `json:"secondaryStaticIpPool,omitempty" tf:"secondary_static_ip_pool,omitempty"`

	// A range of IPs permitted to be used as static IPs for
	// virtual machines; see IP Pools below for details.
	// IP ranges used for static pool allocation in the network
	// +kubebuilder:validation:Optional
	StaticIPPool []NetworkIsolatedV2StaticIPPoolParameters `json:"staticIpPool,omitempty" tf:"static_ip_pool,omitempty"`

	// (Deprecated; Optional) The name of VDC to use. Deprecated  in favor of new field
	// owner_id which supports VDC and VDC Group IDs.
	// The name of VDC to use, optional if defined at provider level
	// +kubebuilder:validation:Optional
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type NetworkIsolatedV2StaticIPPoolInitParameters struct {

	// The final address in the IP Range
	// End address of the IP range
	EndAddress *string `json:"endAddress,omitempty" tf:"end_address,omitempty"`

	// The first address in the IP Range
	// Start address of the IP range
	StartAddress *string `json:"startAddress,omitempty" tf:"start_address,omitempty"`
}

type NetworkIsolatedV2StaticIPPoolObservation struct {

	// The final address in the IP Range
	// End address of the IP range
	EndAddress *string `json:"endAddress,omitempty" tf:"end_address,omitempty"`

	// The first address in the IP Range
	// Start address of the IP range
	StartAddress *string `json:"startAddress,omitempty" tf:"start_address,omitempty"`
}

type NetworkIsolatedV2StaticIPPoolParameters struct {

	// The final address in the IP Range
	// End address of the IP range
	// +kubebuilder:validation:Optional
	EndAddress *string `json:"endAddress" tf:"end_address,omitempty"`

	// The first address in the IP Range
	// Start address of the IP range
	// +kubebuilder:validation:Optional
	StartAddress *string `json:"startAddress" tf:"start_address,omitempty"`
}

type SecondaryStaticIPPoolInitParameters struct {

	// The final address in the IP Range
	// End address of the IP range
	EndAddress *string `json:"endAddress,omitempty" tf:"end_address,omitempty"`

	// The first address in the IP Range
	// Start address of the IP range
	StartAddress *string `json:"startAddress,omitempty" tf:"start_address,omitempty"`
}

type SecondaryStaticIPPoolObservation struct {

	// The final address in the IP Range
	// End address of the IP range
	EndAddress *string `json:"endAddress,omitempty" tf:"end_address,omitempty"`

	// The first address in the IP Range
	// Start address of the IP range
	StartAddress *string `json:"startAddress,omitempty" tf:"start_address,omitempty"`
}

type SecondaryStaticIPPoolParameters struct {

	// The final address in the IP Range
	// End address of the IP range
	// +kubebuilder:validation:Optional
	EndAddress *string `json:"endAddress" tf:"end_address,omitempty"`

	// The first address in the IP Range
	// Start address of the IP range
	// +kubebuilder:validation:Optional
	StartAddress *string `json:"startAddress" tf:"start_address,omitempty"`
}

// NetworkIsolatedV2Spec defines the desired state of NetworkIsolatedV2
type NetworkIsolatedV2Spec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NetworkIsolatedV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NetworkIsolatedV2InitParameters `json:"initProvider,omitempty"`
}

// NetworkIsolatedV2Status defines the observed state of NetworkIsolatedV2.
type NetworkIsolatedV2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NetworkIsolatedV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NetworkIsolatedV2 is the Schema for the NetworkIsolatedV2s API. Provides a VMware Cloud Director Org VDC isolated Network. This can be used to create, modify, and delete isolated VDC networks (backed by NSX-T or NSX-V).
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type NetworkIsolatedV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.gateway) || (has(self.initProvider) && has(self.initProvider.gateway))",message="spec.forProvider.gateway is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.prefixLength) || (has(self.initProvider) && has(self.initProvider.prefixLength))",message="spec.forProvider.prefixLength is a required parameter"
	Spec   NetworkIsolatedV2Spec   `json:"spec"`
	Status NetworkIsolatedV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkIsolatedV2List contains a list of NetworkIsolatedV2s
type NetworkIsolatedV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkIsolatedV2 `json:"items"`
}

// Repository type metadata.
var (
	NetworkIsolatedV2_Kind             = "NetworkIsolatedV2"
	NetworkIsolatedV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NetworkIsolatedV2_Kind}.String()
	NetworkIsolatedV2_KindAPIVersion   = NetworkIsolatedV2_Kind + "." + CRDGroupVersion.String()
	NetworkIsolatedV2_GroupVersionKind = CRDGroupVersion.WithKind(NetworkIsolatedV2_Kind)
)

func init() {
	SchemeBuilder.Register(&NetworkIsolatedV2{}, &NetworkIsolatedV2List{})
}
