// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type NsxvFirewallRuleDestinationInitParameters struct {

	// When the toggle exclusion is selected, the rule is applied to
	// traffic on all sources except for the locations you excluded. When the toggle exclusion is not
	// selected, the rule applies to traffic you specified. Default false. This
	// example uses it.
	// Rule is applied to traffic going to any destinations except for the excluded destination. Default 'false'
	Exclude *bool `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// A set of with either three keywords vse (UI names it as any), internal, external or an org network name. It automatically looks up vNic in the backend.
	// 'vse', 'internal', 'external' or network name
	// +listType=set
	GatewayInterfaces []*string `json:"gatewayInterfaces,omitempty" tf:"gateway_interfaces,omitempty"`

	// A set of IP addresses, CIDRs or ranges. A keyword any is also
	// accepted as a parameter.
	// IP address, CIDR, an IP range, or the keyword 'any'
	// +listType=set
	IPAddresses []*string `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	// A set of existing IP set names (either created manually or configured using vcd_nsxv_ip_set resource)
	// Set of IP set names
	// +listType=set
	IPSets []*string `json:"ipSets,omitempty" tf:"ip_sets,omitempty"`

	// A set of org network names.
	// Set of org network names
	// +listType=set
	OrgNetworks []*string `json:"orgNetworks,omitempty" tf:"org_networks,omitempty"`

	// A set of .id fields of vcd_vapp_vm resources.
	// Set of VM IDs
	// +listType=set
	VMIds []*string `json:"vmIds,omitempty" tf:"vm_ids,omitempty"`
}

type NsxvFirewallRuleDestinationObservation struct {

	// When the toggle exclusion is selected, the rule is applied to
	// traffic on all sources except for the locations you excluded. When the toggle exclusion is not
	// selected, the rule applies to traffic you specified. Default false. This
	// example uses it.
	// Rule is applied to traffic going to any destinations except for the excluded destination. Default 'false'
	Exclude *bool `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// A set of with either three keywords vse (UI names it as any), internal, external or an org network name. It automatically looks up vNic in the backend.
	// 'vse', 'internal', 'external' or network name
	// +listType=set
	GatewayInterfaces []*string `json:"gatewayInterfaces,omitempty" tf:"gateway_interfaces,omitempty"`

	// A set of IP addresses, CIDRs or ranges. A keyword any is also
	// accepted as a parameter.
	// IP address, CIDR, an IP range, or the keyword 'any'
	// +listType=set
	IPAddresses []*string `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	// A set of existing IP set names (either created manually or configured using vcd_nsxv_ip_set resource)
	// Set of IP set names
	// +listType=set
	IPSets []*string `json:"ipSets,omitempty" tf:"ip_sets,omitempty"`

	// A set of org network names.
	// Set of org network names
	// +listType=set
	OrgNetworks []*string `json:"orgNetworks,omitempty" tf:"org_networks,omitempty"`

	// A set of .id fields of vcd_vapp_vm resources.
	// Set of VM IDs
	// +listType=set
	VMIds []*string `json:"vmIds,omitempty" tf:"vm_ids,omitempty"`
}

type NsxvFirewallRuleDestinationParameters struct {

	// When the toggle exclusion is selected, the rule is applied to
	// traffic on all sources except for the locations you excluded. When the toggle exclusion is not
	// selected, the rule applies to traffic you specified. Default false. This
	// example uses it.
	// Rule is applied to traffic going to any destinations except for the excluded destination. Default 'false'
	// +kubebuilder:validation:Optional
	Exclude *bool `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// A set of with either three keywords vse (UI names it as any), internal, external or an org network name. It automatically looks up vNic in the backend.
	// 'vse', 'internal', 'external' or network name
	// +kubebuilder:validation:Optional
	// +listType=set
	GatewayInterfaces []*string `json:"gatewayInterfaces,omitempty" tf:"gateway_interfaces,omitempty"`

	// A set of IP addresses, CIDRs or ranges. A keyword any is also
	// accepted as a parameter.
	// IP address, CIDR, an IP range, or the keyword 'any'
	// +kubebuilder:validation:Optional
	// +listType=set
	IPAddresses []*string `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	// A set of existing IP set names (either created manually or configured using vcd_nsxv_ip_set resource)
	// Set of IP set names
	// +kubebuilder:validation:Optional
	// +listType=set
	IPSets []*string `json:"ipSets,omitempty" tf:"ip_sets,omitempty"`

	// A set of org network names.
	// Set of org network names
	// +kubebuilder:validation:Optional
	// +listType=set
	OrgNetworks []*string `json:"orgNetworks,omitempty" tf:"org_networks,omitempty"`

	// A set of .id fields of vcd_vapp_vm resources.
	// Set of VM IDs
	// +kubebuilder:validation:Optional
	// +listType=set
	VMIds []*string `json:"vmIds,omitempty" tf:"vm_ids,omitempty"`
}

type NsxvFirewallRuleInitParameters struct {

	// This can be used to alter default rule placement order. By default
	// every rule is appended to the end of firewall rule list. When a value of another rule is set - this
	// rule will be placed above the specified rule.
	// This firewall rule will be inserted above the referred one
	AboveRuleID *string `json:"aboveRuleId,omitempty" tf:"above_rule_id,omitempty"`

	// Defines if the rule is set to accept or deny traffic. Default accept
	// 'accept' or 'deny'. Default 'accept'
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// Exactly one block to define source criteria for firewall. See
	// Endpoint and example for usage details.
	Destination []NsxvFirewallRuleDestinationInitParameters `json:"destination,omitempty" tf:"destination,omitempty"`

	// The name of the edge gateway on which to apply the firewall rule.
	// Edge gateway name in which Firewall Rule is located
	EdgeGateway *string `json:"edgeGateway,omitempty" tf:"edge_gateway,omitempty"`

	// Defines if the rule is enabaled. Default true.
	// Whether the rule should be enabled. Default 'true'
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Defines if the logging for this rule is enabaled. Default false.
	// Whether logging should be enabled for this rule. Default 'false'
	LoggingEnabled *bool `json:"loggingEnabled,omitempty" tf:"logging_enabled,omitempty"`

	// Free text name. Can be duplicate.
	// Firewall rule name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful
	// when connected as sysadmin working across different organisations.
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// This can be used to specify user-controlled rule tag. If not specified,
	// it will report rule ID after creation. Must be between 65537-131072.
	// Optional. Allows to set custom rule tag
	RuleTag *float64 `json:"ruleTag,omitempty" tf:"rule_tag,omitempty"`

	// Possible values - user, internal_high.
	// Read only. Possible values 'user', 'internal_high'
	RuleType *string `json:"ruleType,omitempty" tf:"rule_type,omitempty"`

	// One or more blocks to define protocol and port details. Use multiple blocks
	// if you want to define multiple port/protocol combinations for the same rule. See
	// Service and example for usage details.
	Service []ServiceInitParameters `json:"service,omitempty" tf:"service,omitempty"`

	// Exactly one block to define source criteria for firewall. See
	// Endpoint and example for usage details.
	Source []NsxvFirewallRuleSourceInitParameters `json:"source,omitempty" tf:"source,omitempty"`

	// The name of VDC to use, optional if defined at provider level.
	// The name of VDC to use, optional if defined at provider level
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type NsxvFirewallRuleObservation struct {

	// This can be used to alter default rule placement order. By default
	// every rule is appended to the end of firewall rule list. When a value of another rule is set - this
	// rule will be placed above the specified rule.
	// This firewall rule will be inserted above the referred one
	AboveRuleID *string `json:"aboveRuleId,omitempty" tf:"above_rule_id,omitempty"`

	// Defines if the rule is set to accept or deny traffic. Default accept
	// 'accept' or 'deny'. Default 'accept'
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// Exactly one block to define source criteria for firewall. See
	// Endpoint and example for usage details.
	Destination []NsxvFirewallRuleDestinationObservation `json:"destination,omitempty" tf:"destination,omitempty"`

	// The name of the edge gateway on which to apply the firewall rule.
	// Edge gateway name in which Firewall Rule is located
	EdgeGateway *string `json:"edgeGateway,omitempty" tf:"edge_gateway,omitempty"`

	// Defines if the rule is enabaled. Default true.
	// Whether the rule should be enabled. Default 'true'
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Defines if the logging for this rule is enabaled. Default false.
	// Whether logging should be enabled for this rule. Default 'false'
	LoggingEnabled *bool `json:"loggingEnabled,omitempty" tf:"logging_enabled,omitempty"`

	// Free text name. Can be duplicate.
	// Firewall rule name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful
	// when connected as sysadmin working across different organisations.
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// This can be used to specify user-controlled rule tag. If not specified,
	// it will report rule ID after creation. Must be between 65537-131072.
	// Optional. Allows to set custom rule tag
	RuleTag *float64 `json:"ruleTag,omitempty" tf:"rule_tag,omitempty"`

	// Possible values - user, internal_high.
	// Read only. Possible values 'user', 'internal_high'
	RuleType *string `json:"ruleType,omitempty" tf:"rule_type,omitempty"`

	// One or more blocks to define protocol and port details. Use multiple blocks
	// if you want to define multiple port/protocol combinations for the same rule. See
	// Service and example for usage details.
	Service []ServiceObservation `json:"service,omitempty" tf:"service,omitempty"`

	// Exactly one block to define source criteria for firewall. See
	// Endpoint and example for usage details.
	Source []NsxvFirewallRuleSourceObservation `json:"source,omitempty" tf:"source,omitempty"`

	// The name of VDC to use, optional if defined at provider level.
	// The name of VDC to use, optional if defined at provider level
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type NsxvFirewallRuleParameters struct {

	// This can be used to alter default rule placement order. By default
	// every rule is appended to the end of firewall rule list. When a value of another rule is set - this
	// rule will be placed above the specified rule.
	// This firewall rule will be inserted above the referred one
	// +kubebuilder:validation:Optional
	AboveRuleID *string `json:"aboveRuleId,omitempty" tf:"above_rule_id,omitempty"`

	// Defines if the rule is set to accept or deny traffic. Default accept
	// 'accept' or 'deny'. Default 'accept'
	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// Exactly one block to define source criteria for firewall. See
	// Endpoint and example for usage details.
	// +kubebuilder:validation:Optional
	Destination []NsxvFirewallRuleDestinationParameters `json:"destination,omitempty" tf:"destination,omitempty"`

	// The name of the edge gateway on which to apply the firewall rule.
	// Edge gateway name in which Firewall Rule is located
	// +kubebuilder:validation:Optional
	EdgeGateway *string `json:"edgeGateway,omitempty" tf:"edge_gateway,omitempty"`

	// Defines if the rule is enabaled. Default true.
	// Whether the rule should be enabled. Default 'true'
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Defines if the logging for this rule is enabaled. Default false.
	// Whether logging should be enabled for this rule. Default 'false'
	// +kubebuilder:validation:Optional
	LoggingEnabled *bool `json:"loggingEnabled,omitempty" tf:"logging_enabled,omitempty"`

	// Free text name. Can be duplicate.
	// Firewall rule name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful
	// when connected as sysadmin working across different organisations.
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// This can be used to specify user-controlled rule tag. If not specified,
	// it will report rule ID after creation. Must be between 65537-131072.
	// Optional. Allows to set custom rule tag
	// +kubebuilder:validation:Optional
	RuleTag *float64 `json:"ruleTag,omitempty" tf:"rule_tag,omitempty"`

	// Possible values - user, internal_high.
	// Read only. Possible values 'user', 'internal_high'
	// +kubebuilder:validation:Optional
	RuleType *string `json:"ruleType,omitempty" tf:"rule_type,omitempty"`

	// One or more blocks to define protocol and port details. Use multiple blocks
	// if you want to define multiple port/protocol combinations for the same rule. See
	// Service and example for usage details.
	// +kubebuilder:validation:Optional
	Service []ServiceParameters `json:"service,omitempty" tf:"service,omitempty"`

	// Exactly one block to define source criteria for firewall. See
	// Endpoint and example for usage details.
	// +kubebuilder:validation:Optional
	Source []NsxvFirewallRuleSourceParameters `json:"source,omitempty" tf:"source,omitempty"`

	// The name of VDC to use, optional if defined at provider level.
	// The name of VDC to use, optional if defined at provider level
	// +kubebuilder:validation:Optional
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type NsxvFirewallRuleSourceInitParameters struct {

	// When the toggle exclusion is selected, the rule is applied to
	// traffic on all sources except for the locations you excluded. When the toggle exclusion is not
	// selected, the rule applies to traffic you specified. Default false. This
	// example uses it.
	// Rule is applied to traffic coming from all sources except for the excluded source. Default 'false'
	Exclude *bool `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// A set of with either three keywords vse (UI names it as any), internal, external or an org network name. It automatically looks up vNic in the backend.
	// 'vse', 'internal', 'external' or network name
	// +listType=set
	GatewayInterfaces []*string `json:"gatewayInterfaces,omitempty" tf:"gateway_interfaces,omitempty"`

	// A set of IP addresses, CIDRs or ranges. A keyword any is also
	// accepted as a parameter.
	// IP address, CIDR, an IP range, or the keyword 'any'
	// +listType=set
	IPAddresses []*string `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	// A set of existing IP set names (either created manually or configured using vcd_nsxv_ip_set resource)
	// Set of IP set names
	// +listType=set
	IPSets []*string `json:"ipSets,omitempty" tf:"ip_sets,omitempty"`

	// A set of org network names.
	// Set of org network names
	// +listType=set
	OrgNetworks []*string `json:"orgNetworks,omitempty" tf:"org_networks,omitempty"`

	// A set of .id fields of vcd_vapp_vm resources.
	// Set of VM IDs
	// +listType=set
	VMIds []*string `json:"vmIds,omitempty" tf:"vm_ids,omitempty"`
}

type NsxvFirewallRuleSourceObservation struct {

	// When the toggle exclusion is selected, the rule is applied to
	// traffic on all sources except for the locations you excluded. When the toggle exclusion is not
	// selected, the rule applies to traffic you specified. Default false. This
	// example uses it.
	// Rule is applied to traffic coming from all sources except for the excluded source. Default 'false'
	Exclude *bool `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// A set of with either three keywords vse (UI names it as any), internal, external or an org network name. It automatically looks up vNic in the backend.
	// 'vse', 'internal', 'external' or network name
	// +listType=set
	GatewayInterfaces []*string `json:"gatewayInterfaces,omitempty" tf:"gateway_interfaces,omitempty"`

	// A set of IP addresses, CIDRs or ranges. A keyword any is also
	// accepted as a parameter.
	// IP address, CIDR, an IP range, or the keyword 'any'
	// +listType=set
	IPAddresses []*string `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	// A set of existing IP set names (either created manually or configured using vcd_nsxv_ip_set resource)
	// Set of IP set names
	// +listType=set
	IPSets []*string `json:"ipSets,omitempty" tf:"ip_sets,omitempty"`

	// A set of org network names.
	// Set of org network names
	// +listType=set
	OrgNetworks []*string `json:"orgNetworks,omitempty" tf:"org_networks,omitempty"`

	// A set of .id fields of vcd_vapp_vm resources.
	// Set of VM IDs
	// +listType=set
	VMIds []*string `json:"vmIds,omitempty" tf:"vm_ids,omitempty"`
}

type NsxvFirewallRuleSourceParameters struct {

	// When the toggle exclusion is selected, the rule is applied to
	// traffic on all sources except for the locations you excluded. When the toggle exclusion is not
	// selected, the rule applies to traffic you specified. Default false. This
	// example uses it.
	// Rule is applied to traffic coming from all sources except for the excluded source. Default 'false'
	// +kubebuilder:validation:Optional
	Exclude *bool `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// A set of with either three keywords vse (UI names it as any), internal, external or an org network name. It automatically looks up vNic in the backend.
	// 'vse', 'internal', 'external' or network name
	// +kubebuilder:validation:Optional
	// +listType=set
	GatewayInterfaces []*string `json:"gatewayInterfaces,omitempty" tf:"gateway_interfaces,omitempty"`

	// A set of IP addresses, CIDRs or ranges. A keyword any is also
	// accepted as a parameter.
	// IP address, CIDR, an IP range, or the keyword 'any'
	// +kubebuilder:validation:Optional
	// +listType=set
	IPAddresses []*string `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	// A set of existing IP set names (either created manually or configured using vcd_nsxv_ip_set resource)
	// Set of IP set names
	// +kubebuilder:validation:Optional
	// +listType=set
	IPSets []*string `json:"ipSets,omitempty" tf:"ip_sets,omitempty"`

	// A set of org network names.
	// Set of org network names
	// +kubebuilder:validation:Optional
	// +listType=set
	OrgNetworks []*string `json:"orgNetworks,omitempty" tf:"org_networks,omitempty"`

	// A set of .id fields of vcd_vapp_vm resources.
	// Set of VM IDs
	// +kubebuilder:validation:Optional
	// +listType=set
	VMIds []*string `json:"vmIds,omitempty" tf:"vm_ids,omitempty"`
}

type ServiceInitParameters struct {

	// Port number or range separated by - for port number. Default 'any'.
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// One of any, tcp, udp, icmp to apply.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// Port number or range separated by - for port number. Default 'any'.
	SourcePort *string `json:"sourcePort,omitempty" tf:"source_port,omitempty"`
}

type ServiceObservation struct {

	// Port number or range separated by - for port number. Default 'any'.
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// One of any, tcp, udp, icmp to apply.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// Port number or range separated by - for port number. Default 'any'.
	SourcePort *string `json:"sourcePort,omitempty" tf:"source_port,omitempty"`
}

type ServiceParameters struct {

	// Port number or range separated by - for port number. Default 'any'.
	// +kubebuilder:validation:Optional
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// One of any, tcp, udp, icmp to apply.
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol" tf:"protocol,omitempty"`

	// Port number or range separated by - for port number. Default 'any'.
	// +kubebuilder:validation:Optional
	SourcePort *string `json:"sourcePort,omitempty" tf:"source_port,omitempty"`
}

// NsxvFirewallRuleSpec defines the desired state of NsxvFirewallRule
type NsxvFirewallRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NsxvFirewallRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NsxvFirewallRuleInitParameters `json:"initProvider,omitempty"`
}

// NsxvFirewallRuleStatus defines the observed state of NsxvFirewallRule.
type NsxvFirewallRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NsxvFirewallRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NsxvFirewallRule is the Schema for the NsxvFirewallRules API. Provides a VMware Cloud Director firewall rule resource for advanced edge gateways (NSX-V). This can be used to create, modify, and delete firewall rules.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type NsxvFirewallRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.destination) || (has(self.initProvider) && has(self.initProvider.destination))",message="spec.forProvider.destination is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.edgeGateway) || (has(self.initProvider) && has(self.initProvider.edgeGateway))",message="spec.forProvider.edgeGateway is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.service) || (has(self.initProvider) && has(self.initProvider.service))",message="spec.forProvider.service is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.source) || (has(self.initProvider) && has(self.initProvider.source))",message="spec.forProvider.source is a required parameter"
	Spec   NsxvFirewallRuleSpec   `json:"spec"`
	Status NsxvFirewallRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NsxvFirewallRuleList contains a list of NsxvFirewallRules
type NsxvFirewallRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NsxvFirewallRule `json:"items"`
}

// Repository type metadata.
var (
	NsxvFirewallRule_Kind             = "NsxvFirewallRule"
	NsxvFirewallRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NsxvFirewallRule_Kind}.String()
	NsxvFirewallRule_KindAPIVersion   = NsxvFirewallRule_Kind + "." + CRDGroupVersion.String()
	NsxvFirewallRule_GroupVersionKind = CRDGroupVersion.WithKind(NsxvFirewallRule_Kind)
)

func init() {
	SchemeBuilder.Register(&NsxvFirewallRule{}, &NsxvFirewallRuleList{})
}
