// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CriteriaInitParameters struct {

	// Up to 4 rules for matching VMs. List of rules are matched with boolean AND
	// operation and all defines rules must match to include object. See Rule for rule
	// definition structure.
	// Up to 4 rules can be used to define single criteria (VCD 10.2, 10.3)
	Rule []CriteriaRuleInitParameters `json:"rule,omitempty" tf:"rule,omitempty"`
}

type CriteriaObservation struct {

	// Up to 4 rules for matching VMs. List of rules are matched with boolean AND
	// operation and all defines rules must match to include object. See Rule for rule
	// definition structure.
	// Up to 4 rules can be used to define single criteria (VCD 10.2, 10.3)
	Rule []CriteriaRuleObservation `json:"rule,omitempty" tf:"rule,omitempty"`
}

type CriteriaParameters struct {

	// Up to 4 rules for matching VMs. List of rules are matched with boolean AND
	// operation and all defines rules must match to include object. See Rule for rule
	// definition structure.
	// Up to 4 rules can be used to define single criteria (VCD 10.2, 10.3)
	// +kubebuilder:validation:Optional
	Rule []CriteriaRuleParameters `json:"rule,omitempty" tf:"rule,omitempty"`
}

type CriteriaRuleInitParameters struct {

	// Supported operators depend on type. VM_TAG supports 4 operator types
	// with self explanatory names:
	// Operator can be one of 'EQUALS', 'CONTAINS', 'STARTS_WITH', 'ENDS_WITH'
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`

	// VM_NAME or VM_TAG
	// Type of object matching 'VM_TAG' or 'VM_NAME'
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// String to evaluate by given type and operator
	// Filter value
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type CriteriaRuleObservation struct {

	// Supported operators depend on type. VM_TAG supports 4 operator types
	// with self explanatory names:
	// Operator can be one of 'EQUALS', 'CONTAINS', 'STARTS_WITH', 'ENDS_WITH'
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`

	// VM_NAME or VM_TAG
	// Type of object matching 'VM_TAG' or 'VM_NAME'
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// String to evaluate by given type and operator
	// Filter value
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type CriteriaRuleParameters struct {

	// Supported operators depend on type. VM_TAG supports 4 operator types
	// with self explanatory names:
	// Operator can be one of 'EQUALS', 'CONTAINS', 'STARTS_WITH', 'ENDS_WITH'
	// +kubebuilder:validation:Optional
	Operator *string `json:"operator" tf:"operator,omitempty"`

	// VM_NAME or VM_TAG
	// Type of object matching 'VM_TAG' or 'VM_NAME'
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`

	// String to evaluate by given type and operator
	// Filter value
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type MemberVmsInitParameters struct {
}

type MemberVmsObservation struct {

	// Member VM ID
	VMID *string `json:"vmId,omitempty" tf:"vm_id,omitempty"`

	// Member VM name
	VMName *string `json:"vmName,omitempty" tf:"vm_name,omitempty"`

	// Parent vApp ID for member VM (empty for standalone VMs)
	VappID *string `json:"vappId,omitempty" tf:"vapp_id,omitempty"`

	// Parent vApp Name for member VM (empty for standalone VMs)
	VappName *string `json:"vappName,omitempty" tf:"vapp_name,omitempty"`
}

type MemberVmsParameters struct {
}

type NsxtDynamicSecurityGroupInitParameters struct {

	// Up to 3 criteria for matching VMs. List of criteria is matched with boolean
	// OR operation and matching any of defined criteria will include objects. Each criteria can
	// contains up to 4 rule definitions.
	// Up to 3 criteria to be used to define the Dynamic Security Group (VCD 10.2, 10.3)
	Criteria []CriteriaInitParameters `json:"criteria,omitempty" tf:"criteria,omitempty"`

	// An optional description of the Dynamic Security Group
	// Dynamic Security Group description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A unique name for Dynamic Security Group
	// Dynamic Security Group name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful
	// when connected as sysadmin working across different organisations.
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// VDC Group ID for Dynamic Security Group creation.
	// VDC Group ID in which Dynamic Security Group is located
	VdcGroupID *string `json:"vdcGroupId,omitempty" tf:"vdc_group_id,omitempty"`
}

type NsxtDynamicSecurityGroupObservation struct {

	// Up to 3 criteria for matching VMs. List of criteria is matched with boolean
	// OR operation and matching any of defined criteria will include objects. Each criteria can
	// contains up to 4 rule definitions.
	// Up to 3 criteria to be used to define the Dynamic Security Group (VCD 10.2, 10.3)
	Criteria []CriteriaObservation `json:"criteria,omitempty" tf:"criteria,omitempty"`

	// An optional description of the Dynamic Security Group
	// Dynamic Security Group description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A set of member VMs (if exist). see Member VMs below for details.
	// Set of VM IDs
	MemberVms []MemberVmsObservation `json:"memberVms,omitempty" tf:"member_vms,omitempty"`

	// A unique name for Dynamic Security Group
	// Dynamic Security Group name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful
	// when connected as sysadmin working across different organisations.
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// VDC Group ID for Dynamic Security Group creation.
	// VDC Group ID in which Dynamic Security Group is located
	VdcGroupID *string `json:"vdcGroupId,omitempty" tf:"vdc_group_id,omitempty"`
}

type NsxtDynamicSecurityGroupParameters struct {

	// Up to 3 criteria for matching VMs. List of criteria is matched with boolean
	// OR operation and matching any of defined criteria will include objects. Each criteria can
	// contains up to 4 rule definitions.
	// Up to 3 criteria to be used to define the Dynamic Security Group (VCD 10.2, 10.3)
	// +kubebuilder:validation:Optional
	Criteria []CriteriaParameters `json:"criteria,omitempty" tf:"criteria,omitempty"`

	// An optional description of the Dynamic Security Group
	// Dynamic Security Group description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A unique name for Dynamic Security Group
	// Dynamic Security Group name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful
	// when connected as sysadmin working across different organisations.
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// VDC Group ID for Dynamic Security Group creation.
	// VDC Group ID in which Dynamic Security Group is located
	// +kubebuilder:validation:Optional
	VdcGroupID *string `json:"vdcGroupId,omitempty" tf:"vdc_group_id,omitempty"`
}

// NsxtDynamicSecurityGroupSpec defines the desired state of NsxtDynamicSecurityGroup
type NsxtDynamicSecurityGroupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NsxtDynamicSecurityGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NsxtDynamicSecurityGroupInitParameters `json:"initProvider,omitempty"`
}

// NsxtDynamicSecurityGroupStatus defines the observed state of NsxtDynamicSecurityGroup.
type NsxtDynamicSecurityGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NsxtDynamicSecurityGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NsxtDynamicSecurityGroup is the Schema for the NsxtDynamicSecurityGroups API. Provides a resource to manage NSX-T Dynamic Security Groups. Dynamic Security Groups group Virtual Machines based on specific criteria (VM Names or Security tags) to which Distributed Firewall Rules apply.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type NsxtDynamicSecurityGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vdcGroupId) || (has(self.initProvider) && has(self.initProvider.vdcGroupId))",message="spec.forProvider.vdcGroupId is a required parameter"
	Spec   NsxtDynamicSecurityGroupSpec   `json:"spec"`
	Status NsxtDynamicSecurityGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NsxtDynamicSecurityGroupList contains a list of NsxtDynamicSecurityGroups
type NsxtDynamicSecurityGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NsxtDynamicSecurityGroup `json:"items"`
}

// Repository type metadata.
var (
	NsxtDynamicSecurityGroup_Kind             = "NsxtDynamicSecurityGroup"
	NsxtDynamicSecurityGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NsxtDynamicSecurityGroup_Kind}.String()
	NsxtDynamicSecurityGroup_KindAPIVersion   = NsxtDynamicSecurityGroup_Kind + "." + CRDGroupVersion.String()
	NsxtDynamicSecurityGroup_GroupVersionKind = CRDGroupVersion.WithKind(NsxtDynamicSecurityGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&NsxtDynamicSecurityGroup{}, &NsxtDynamicSecurityGroupList{})
}
