apiVersion: vcd.upbound.io/v1alpha1
kind: ClonedvApp
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/clonedvapp
  labels:
    testing.upbound.io/example-name: vapp_from_template
  name: vapp-from-template
spec:
  forProvider:
    description: vApp from template
    name: VappFromTemplate
    powerOn: true
    sourceId: ${data.vcd_catalog_vapp_template.tmpl.id}
    sourceType: template
