apiVersion: vcd.upbound.io/v1alpha1
kind: EdgegatewayVPN
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/edgegatewayvpn
  labels:
    testing.upbound.io/example-name: vpn
  name: vpn
spec:
  forProvider:
    description: Description
    edgeGateway: Internet_01(nti0000bi2_123-456-2)
    encryptionProtocol: AES256
    localId: 64.121.123.10
    localIpAddress: 64.121.123.10
    localSubnets:
    - localSubnetGateway: 10.0.1.1
      localSubnetMask: 255.255.255.0
      localSubnetName: DMZ_EAST
    - localSubnetGateway: 10.0.22.1
      localSubnetMask: 255.255.255.0
      localSubnetName: WEB_EAST
    mtu: 1400
    name: west-to-east
    peerId: 64.121.123.11
    peerIpAddress: 64.121.123.11
    peerSubnets:
    - peerSubnetGateway: 10.0.10.1
      peerSubnetMask: 255.255.255.0
      peerSubnetName: DMZ_WEST
    - peerSubnetGateway: 10.0.20.1
      peerSubnetMask: 255.255.255.0
      peerSubnetName: WEB_WEST
    sharedSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
