apiVersion: vcd.upbound.io/v1alpha1
kind: ExternalNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/externalnetwork
  labels:
    testing.upbound.io/example-name: net
  name: net
spec:
  forProvider:
    description: Reference for vCD external network
    ipScope:
    - dns1: 192.168.0.164
      dns2: 192.168.0.196
      dnsSuffix: mybiz.biz
      gateway: 192.168.30.49
      netmask: 255.255.255.240
      staticIpPool:
      - endAddress: 192.168.30.62
        startAddress: 192.168.30.51
    - dns1: 192.168.1.164
      dns2: 192.168.1.196
      dnsSuffix: my.biz
      gateway: 192.168.31.49
      netmask: 255.255.255.240
      staticIpPool:
      - endAddress: 192.168.31.55
        startAddress: 192.168.31.51
      - endAddress: 192.168.31.59
        startAddress: 192.168.31.57
    name: my-ext-net
    retainNetInfoAcrossDeployments: false
    vsphereNetwork:
    - name: myNetwork
      type: DV_PORTGROUP
      vcenter: vcenter-name
    - name: myNetwork2
      type: DV_PORTGROUP
      vcenter: vcenter-name2

---

apiVersion: vcd.upbound.io/v1alpha1
kind: NetworkDirect
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/externalnetwork
  labels:
    testing.upbound.io/example-name: net
  name: net
spec:
  forProvider:
    externalNetwork: my-ext-net
    name: my-net
    org: my-org
    vdc: my-vdc
