apiVersion: vcd.upbound.io/v1alpha1
kind: IndependentDisk
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/independentdisk
  labels:
    testing.upbound.io/example-name: myNewIndependentDisk
  name: mynewindependentdisk
spec:
  forProvider:
    busSubType: VirtualSCSI
    busType: SCSI
    name: logDisk
    sizeInMb: "1024"
    storageProfile: external
    vdc: my-vcd

---

apiVersion: vcd.upbound.io/v1alpha1
kind: VAppVm
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/independentdisk
  labels:
    testing.upbound.io/example-name: web2
  name: web2
spec:
  forProvider:
    disk:
    - busNumber: 1
      name: logDisk
      unitNumber: 0
    vappName: ${vcd_vapp.web.name}
