apiVersion: vcd.upbound.io/v1alpha1
kind: LbServiceMonitor
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/lbservicemonitor
  labels:
    testing.upbound.io/example-name: monitor
  name: monitor
spec:
  forProvider:
    edgeGateway: my-edge-gw
    extension:
      content-type: application/json
      linespan: ""
    interval: "5"
    maxRetries: "3"
    method: GET
    name: http-monitor
    org: my-org
    send: '{"key": "value"}'
    timeout: "20"
    type: http
    url: /health
    vdc: my-org-vdc
