apiVersion: vcd.upbound.io/v1alpha1
kind: NetworkIsolatedV2
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/networkisolatedv2
  labels:
    testing.upbound.io/example-name: nsxt-backed
  name: nsxt-backed
spec:
  forProvider:
    description: My isolated Org VDC network backed by NSX-T
    gateway: 1.1.1.1
    guestVlanAllowed: true
    name: nsxt-isolated 1
    org: my-org
    ownerId: ${data.vcd_org_vdc.main.id}
    prefixLength: 24
    staticIpPool:
    - endAddress: 1.1.1.20
      startAddress: 1.1.1.10
    - endAddress: 1.1.1.103
      startAddress: 1.1.1.100
