apiVersion: vcd.upbound.io/v1alpha1
kind: NetworkRouted
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/networkrouted
  labels:
    testing.upbound.io/example-name: net
  name: net
spec:
  forProvider:
    dhcpPool:
    - endAddress: 10.10.0.100
      startAddress: 10.10.0.2
    edgeGateway: Edge Gateway Name
    gateway: 10.10.0.1
    name: my-net
    org: my-org
    staticIpPool:
    - endAddress: 10.10.0.254
      startAddress: 10.10.0.152
    vdc: my-vdc
