apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtAlbVirtualService
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtalbvirtualservice
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    applicationProfileType: HTTP
    edgeGatewayId: ${data.vcd_nsxt_edgegateway.existing.id}
    name: new-virtual-service
    org: my-org
    poolId: ${vcd_nsxt_alb_pool.test.id}
    serviceEngineGroupId: ${vcd_nsxt_alb_edgegateway_service_engine_group.assignment.service_engine_group_id}
    servicePort:
    - startPort: 80
      type: TCP_PROXY
    virtualIpAddress: ${tolist(data.vcd_nsxt_edgegateway.existing.subnet)[0].primary_ip}

---

apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtAlbPool
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtalbvirtualservice
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    edgeGatewayId: ${data.vcd_nsxt_edgegateway.existing.id}
    name: test-pool
    org: my-org
