apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtEdgeGatewayBgpNeighbor
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtedgegatewaybgpneighbor
  labels:
    testing.upbound.io/example-name: neighbor-one
  name: neighbor-one
spec:
  forProvider:
    allowAsIn: false
    bfdDeadMultiple: 5
    bfdEnabled: true
    bfdInterval: 800
    edgeGatewayId: ${data.vcd_nsxt_edgegateway.testing.id}
    gracefulRestartMode: GRACEFUL_AND_HELPER
    holdDownTimer: 400
    inFilterIpPrefixListId: ${data.vcd_nsxt_edgegateway_bgp_ip_prefix_list.in-1.id}
    ipAddress: 1.1.1.1
    keepAliveTimer: 78
    org: datacloud
    outFilterIpPrefixListId: ${data.vcd_nsxt_edgegateway_bgp_ip_prefix_list.out-1.id}
    remoteAsNumber: "62513"
    routeFiltering: IPV4
