apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtAlbCloud
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtalbcloud
  labels:
    testing.upbound.io/example-name: first
  name: first
spec:
  forProvider:
    controllerId: ${data.vcd_nsxt_alb_controller.main.id}
    description: ALB Cloud
    importableCloudId: ${data.vcd_nsxt_alb_importable_cloud.cld.id}
    name: nsxt-cloud
    networkPoolId: ${data.vcd_nsxt_alb_importable_cloud.cld.network_pool_id}
