apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtRouteAdvertisement
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtrouteadvertisement
  labels:
    testing.upbound.io/example-name: my_route_advertisement
  name: my-route-advertisement
spec:
  forProvider:
    edgeGatewayId: ${data.vcd_nsxt_edgegateway.my_edge_gateway.id}
    enabled: true
    subnets:
    - 192.168.1.0/24
    - 192.168.2.0/24
