apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtAlbController
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtalbcontroller
  labels:
    testing.upbound.io/example-name: first
  name: first
spec:
  forProvider:
    description: first alb controller
    licenseType: ENTERPRISE
    name: aviController1
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    url: https://my.controller
    username: admin
