apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtEdgegatewayBgpConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtedgegatewaybgpconfiguration
  labels:
    testing.upbound.io/example-name: testing
  name: testing
spec:
  forProvider:
    ecmpEnabled: true
    edgeGatewayId: ${data.vcd_nsxt_edgegateway.testing.id}
    enabled: false
    gracefulRestartMode: HELPER_ONLY
    gracefulRestartTimer: 190
    localAsNumber: "65430"
    org: my-org
    staleRouteTimer: 600
