apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtIpsecVpnTunnel
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtipsecvpntunnel
  labels:
    testing.upbound.io/example-name: tunnel1
  name: tunnel1
spec:
  forProvider:
    description: testing tunnel
    edgeGatewayId: ${data.vcd_nsxt_edgegateway.existing.id}
    localIpAddress: ${tolist(data.vcd_nsxt_edgegateway.existing_gw.subnet)[0].primary_ip}
    localNetworks:
    - 10.10.10.0/24
    - 30.30.30.0/28
    - 40.40.40.1/32
    name: First
    org: my-org
    preSharedKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    remoteIpAddress: 1.2.3.4
    remoteNetworks:
    - 192.168.1.0/24
    - 192.168.10.0/24
    - 192.168.20.0/28
