apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtDynamicSecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtdynamicsecuritygroup
  labels:
    testing.upbound.io/example-name: group1
  name: group1
spec:
  forProvider:
    criteria:
    - rule:
      - operator: EQUALS
        type: VM_TAG
        value: tag-equals
      - operator: CONTAINS
        type: VM_TAG
        value: tag-contains
      - operator: STARTS_WITH
        type: VM_TAG
        value: tag-starts-with
      - operator: ENDS_WITH
        type: VM_TAG
        value: tag-ends-with
    - rule:
      - operator: CONTAINS
        type: VM_NAME
        value: name-contains-4
      - operator: STARTS_WITH
        type: VM_NAME
        value: starts_with2
      - operator: CONTAINS
        type: VM_NAME
        value: name-contains-22
      - operator: STARTS_WITH
        type: VM_NAME
        value: starts_with22
    - rule:
      - operator: CONTAINS
        type: VM_NAME
        value: name-contains3
      - operator: STARTS_WITH
        type: VM_NAME
        value: starts_with3
      - operator: CONTAINS
        type: VM_NAME
        value: name-contains33
      - operator: STARTS_WITH
        type: VM_NAME
        value: starts_with33
    name: dynamic-security-group-example
    org: cloud
    vdcGroupId: ${data.vcd_vdc_group.group1.id}
