apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtAlbServiceEngineGroup
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtalbserviceenginegroup
  labels:
    testing.upbound.io/example-name: first
  name: first
spec:
  forProvider:
    albCloudId: ${vcd_nsxt_alb_cloud.first.id}
    description: Service Engine for Terraform documentation
    importableServiceEngineGroupName: Default-Group
    name: demo-service-engine
    reservationModel: SHARED
    syncOnRefresh: false

---

apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtAlbCloud
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtalbserviceenginegroup
  labels:
    testing.upbound.io/example-name: first
  name: first
spec:
  forProvider:
    controllerId: ${vcd_nsxt_alb_controller.first.id}
    description: first alb cloud
    importableCloudId: ${data.vcd_nsxt_alb_importable_cloud.cld.id}
    name: nsxt-cloud
    networkPoolId: ${data.vcd_nsxt_alb_importable_cloud.cld.network_pool_id}

---

apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtAlbController
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtalbserviceenginegroup
  labels:
    testing.upbound.io/example-name: first
  name: first
spec:
  forProvider:
    description: first alb controller
    licenseType: ENTERPRISE
    name: aviController1
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    url: https://controller.myXZ
    username: admin
