apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtNetworkImported
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtnetworkimported
  labels:
    testing.upbound.io/example-name: nsxt-backed
  name: nsxt-backed
spec:
  forProvider:
    description: My NSX-T VDC Imported network type
    gateway: 1.1.1.1
    name: nsxt-imported
    nsxtLogicalSwitchName: nsxt_segment_name
    org: my-org
    ownerId: ${data.vcd_org_vdc.main.id}
    prefixLength: 24
    staticIpPool:
    - endAddress: 1.1.1.20
      startAddress: 1.1.1.10
    - endAddress: 1.1.1.103
      startAddress: 1.1.1.100
