apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtNetworkDhcp
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtnetworkdhcp
  labels:
    testing.upbound.io/example-name: pools
  name: pools
spec:
  forProvider:
    orgNetworkId: ${vcd_network_routed_v2.parent-network.id}
    pool:
    - endAddress: 7.1.1.110
      startAddress: 7.1.1.100
    - endAddress: 7.1.1.112
      startAddress: 7.1.1.111

---

apiVersion: vcd.upbound.io/v1alpha1
kind: NetworkRoutedV2
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtnetworkdhcp
  labels:
    testing.upbound.io/example-name: parent-network
  name: parent-network
spec:
  forProvider:
    edgeGatewayId: ${data.vcd_nsxt_edgegateway.existing.id}
    gateway: 7.1.1.1
    name: nsxt-routed-dhcp
    prefixLength: 24
    staticIpPool:
    - endAddress: 7.1.1.20
      startAddress: 7.1.1.10
