apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtAppPortProfile
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtappportprofile
  labels:
    testing.upbound.io/example-name: icmpv4
  name: icmpv4
spec:
  forProvider:
    appPort:
    - protocol: ICMPv4
    contextId: ${data.vcd_nsxt_manager.first.id}
    description: Application port profile for ICMPv4
    name: ICMP custom profile
    org: System
    scope: PROVIDER
