apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtIpSet
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtipset
  labels:
    testing.upbound.io/example-name: set1
  name: set1
spec:
  forProvider:
    description: IP Set containing IPv4 and IPv6 ranges
    edgeGatewayId: ${data.vcd_nsxt_edgegateway.main.id}
    ipAddresses:
    - 12.12.12.1
    - 10.10.10.0/24
    - 11.11.11.1-11.11.11.2
    - 2001:db8::/48
    - 2001:db6:0:0:0:0:0:0-2001:db6:0:ffff:ffff:ffff:ffff:ffff
    name: first-ip-set
    org: my-org
