apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtEdgeGatewayRateLimit
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtedgegatewayratelimit
  labels:
    testing.upbound.io/example-name: testing-in-vdc
  name: testing-in-vdc
spec:
  forProvider:
    edgeGatewayId: ${data.vcd_nsxt_edgegateway.testing-in-vdc.id}
    egressProfileId: ${data.vcd_nsxt_edgegateway_qos_profile.qos-1.id}
    ingressProfileId: ${data.vcd_nsxt_edgegateway_qos_profile.qos-1.id}
    org: datacloud
