apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtDistributedFirewall
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtdistributedfirewall
  labels:
    testing.upbound.io/example-name: t1
  name: t1
spec:
  forProvider:
    org: my-org
    rule:
    - action: ALLOW
      appPortProfileIds:
      - ${data.vcd_nsxt_app_port_profile.WINS.id}
      - ${data.vcd_nsxt_app_port_profile.FTP.id}
      comment: My first rule to allow everything
      description: description
      name: rule1
      sourceGroupsExcluded: true
      sourceIds:
      - ${data.vcd_nsxt_ip_set.set1.id}
      - ${data.vcd_nsxt_ip_set.set2.id}
    - action: DROP
      direction: IN_OUT
      enabled: false
      logging: true
      name: rule2
      networkContextProfileIds:
      - ${vcd_nsxt_network_context_profile.cp1.id}
    - action: REJECT
      ipProtocol: IPV4
      name: rule3
    - action: ALLOW
      destinationGroupsExcluded: false
      direction: OUT
      ipProtocol: IPV6
      name: rule4
      sourceGroupsExcluded: false
    - action: ALLOW
      direction: IN
      ipProtocol: IPV6
      name: rule5
    vdcGroupId: ${vcd_vdc_group.existing.id}
