apiVersion: vcd.upbound.io/v1alpha1
kind: NsxtEdgeGatewayStaticRoute
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxtedgegatewaystaticroute
  labels:
    testing.upbound.io/example-name: sr
  name: sr
spec:
  forProvider:
    description: description for the route
    edgeGatewayId: ${data.vcd_nsxt_edgegateway.existing.id}
    name: some-static-route
    networkCidr: 192.168.1.0/24
    nextHop:
    - adminDistance: 4
      ipAddress: 1.1.1.1
      scope:
      - id: ${data.vcd_network_routed_v2.net.id}
        type: NETWORK
    - adminDistance: 3
      ipAddress: 1.1.1.254
      scope:
      - id: ${data.vcd_network_routed_v2.net.id}
        type: NETWORK
