apiVersion: vcd.upbound.io/v1alpha1
kind: NsxvDistributedFirewall
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxvdistributedfirewall
  labels:
    testing.upbound.io/example-name: dfw1
  name: dfw1
spec:
  forProvider:
    rule:
    - action: allow
      application:
      - destinationPort: "20251"
        protocol: TCP
        sourcePort: "20250"
      - name: ${data.vcd_nsxv_application.application1.name}
        type: Application
        value: ${data.vcd_nsxv_application.application1.id}
      - name: ${data.vcd_nsxv_application_group.application_group1.name}
        type: ApplicationGroup
        value: ${data.vcd_nsxv_application_group.application_group1.id}
      appliedTo:
      - name: ${data.vcd_edgegateway.edge.name}
        type: Edge
        value: ${data.vcd_edgegateway.edge.id}
      direction: inout
      name: third
      source:
      - name: ${data.vcd_nsxv_ip_set.test-ipset.name}
        type: IPSet
        value: ${data.vcd_nsxv_ip_set.test-ipset.id}
    - action: allow
      appliedTo:
      - name: ${data.vcd_org_vdc.my-vdc.name}
        type: VDC
        value: ${data.vcd_org_vdc.my-vdc.id}
      destination:
      - name: ${data.vcd_network_routed.net-r.name}
        type: Network
        value: ${data.vcd_network_routed.net-r.id}
      - name: ${data.vcd_network_isolated.net-i.name}
        type: Network
        value: ${data.vcd_network_isolated.net-i.id}
      direction: inout
      name: second
      source:
      - name: 10.10.1.0-10.10.1.100
        type: Ipv4Address
        value: 10.10.1.0-10.10.1.100
      - name: ${data.vcd_vapp_vm.vm1.name}
        type: VirtualMachine
        value: ${data.vcd_vapp_vm.vm1.id}
    - action: deny
      appliedTo:
      - name: ${data.vcd_org_vdc.my-vdc.name}
        type: VDC
        value: ${data.vcd_org_vdc.my-vdc.id}
      direction: inout
      name: first
    vdcId: ${data.vcd_org_vdc.my-vdc.id}
