apiVersion: vcd.upbound.io/v1alpha1
kind: NsxvFirewallRule
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/nsxvfirewallrule
  labels:
    testing.upbound.io/example-name: my-rule-1
  name: my-rule-1
spec:
  forProvider:
    destination:
    - ipAddresses:
      - ${data.vcd_edgegateway.mygw.default_external_network_ip}
    edgeGateway: my-edge-gateway
    org: my-org
    service:
    - protocol: any
    source:
    - ipSets:
      - ${vcd_ipset.test-ipset2.name}
    vdc: my-vdc
