apiVersion: vcd.upbound.io/v1alpha1
kind: Org
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/org
  labels:
    testing.upbound.io/example-name: my-org
  name: my-org
spec:
  forProvider:
    accountLockout:
    - enabled: true
      invalidLoginsBeforeLockout: 10
      lockoutIntervalMinutes: 60
    deleteForce: true
    deleteRecursive: true
    description: The pride of my work
    fullName: My organization
    isEnabled: true
    name: my-org
    vappLease:
    - deleteOnStorageLeaseExpiration: false
      maximumRuntimeLeaseInSec: 3600
      maximumStorageLeaseInSec: 0
      powerOffOnRuntimeLeaseExpiration: true
    vappTemplateLease:
    - deleteOnStorageLeaseExpiration: true
      maximumStorageLeaseInSec: 604800
