apiVersion: vcd.upbound.io/v1alpha1
kind: OrgGroup
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/orggroup
  labels:
    testing.upbound.io/example-name: org1
  name: org1
spec:
  forProvider:
    name: Org1-AdminGroup
    org: org1
    providerType: SAML
    role: Organization Administrator
