apiVersion: vcd.upbound.io/v1alpha1
kind: OrgUser
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/orguser
  labels:
    testing.upbound.io/example-name: my-org-admin
  name: my-org-admin
spec:
  forProvider:
    description: a new org admin
    name: my-org-admin
    org: my-org
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    role: Organization Administrator
