apiVersion: vcd.upbound.io/v1alpha1
kind: OrgVdcAccessControl
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/orgvdcaccesscontrol
  labels:
    testing.upbound.io/example-name: my_access_control
  name: my-access-control
spec:
  forProvider:
    org: my-org
    sharedWith:
    - accessLevel: ReadOnly
      userId: ${data.vcd_org_user.my-user.id}
    - accessLevel: ReadOnly
      userId: ${data.vcd_org_user.my-user2.id}
    sharedWithEveryone: false
    vdc: my-vdc
