apiVersion: vcd.upbound.io/v1alpha1
kind: ProviderVdc
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/providervdc
  labels:
    testing.upbound.io/example-name: pvdc1
  name: pvdc1
spec:
  forProvider:
    description: new provider VDC
    highestSupportedHardwareVersion: ${data.vcd_resource_pool.rp1.hardware_version}
    isEnabled: true
    name: myPvdc
    networkPoolIds:
    - ${data.vcd_network_pool.np1.id}
    nsxtManagerId: ${data.vcd_nsxt_manager.mgr1.id}
    resourcePoolIds:
    - ${data.vcd_resource_pool.rp1.id}
    storageProfileNames:
    - Development
    vcenterId: ${data.vcd_vcenter.vcenter1.id}
