apiVersion: vcd.upbound.io/v1alpha1
kind: RdeTypeBehavior
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/rdetypebehavior
  labels:
    testing.upbound.io/example-name: my_rde_type_behavior
  name: my-rde-type-behavior
spec:
  forProvider:
    execution:
      id: addNodeOverridden
      type: Activity
    rdeInterfaceBehaviorId: ${vcd_rde_interface_behavior.my_interface_behavior.id}
    rdeTypeId: ${vcd_rde_type.my_rde_type.id}

---

apiVersion: vcd.upbound.io/v1alpha1
kind: RdeInterfaceBehavior
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/rdetypebehavior
  labels:
    testing.upbound.io/example-name: my_interface_behavior
  name: my-interface-behavior
spec:
  forProvider:
    description: |
      Adds a node to the cluster.
      Parameters:
        clusterId: the ID of the cluster
        node: The node address
    execution:
      id: addNode
      type: Activity
    name: MyBehavior
    rdeInterfaceId: ${vcd_rde_interface.my_interface.id}

---

apiVersion: vcd.upbound.io/v1alpha1
kind: RdeType
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/rdetypebehavior
  labels:
    testing.upbound.io/example-name: my_rde_type
  name: my-rde-type
spec:
  forProvider:
    interfaceIds:
    - ${data.vcd_rde_interface.my_interface.id}
    name: My VMware RDE Type
    nss: vcd
    schema: ${file("${path.module}/schemas/my-type-schema.json")}
    vendor: vmware
    version: 4.5.6
