apiVersion: vcd.upbound.io/v1alpha1
kind: RdeTypeBehaviorAcl
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/rdetypebehavioracl
  labels:
    testing.upbound.io/example-name: acl1
  name: acl1
spec:
  forProvider:
    accessLevelIds:
    - urn:vcloud:accessLevel:ReadOnly
    behaviorId: ${vcd_rde_type_behavior.behavior_override.id}
    rdeTypeId: ${vcd_rde_type.type.id}

---

apiVersion: vcd.upbound.io/v1alpha1
kind: RdeInterface
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/rdetypebehavioracl
  labels:
    testing.upbound.io/example-name: interface
  name: interface
spec:
  forProvider:
    name: MyInterface
    nss: nss
    vendor: vendor
    version: 1.0.0

---

apiVersion: vcd.upbound.io/v1alpha1
kind: RdeInterfaceBehavior
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/rdetypebehavioracl
  labels:
    testing.upbound.io/example-name: behavior1
  name: behavior1
spec:
  forProvider:
    description: My Behavior Contract goes here
    execution:
      id: MyActivity1
      type: noop
    name: MyInterfaceBehavior1
    rdeInterfaceId: ${vcd_rde_interface.interface.id}

---

apiVersion: vcd.upbound.io/v1alpha1
kind: RdeInterfaceBehavior
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/rdetypebehavioracl
  labels:
    testing.upbound.io/example-name: behavior2
  name: behavior2
spec:
  forProvider:
    description: My Behavior Contract goes here
    execution:
      id: MyActivity2
      type: noop
    name: MyInterfaceBehavior2
    rdeInterfaceId: ${vcd_rde_interface.interface.id}

---

apiVersion: vcd.upbound.io/v1alpha1
kind: RdeType
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/rdetypebehavioracl
  labels:
    testing.upbound.io/example-name: type
  name: type
spec:
  forProvider:
    description: Type Description
    interfaceIds:
    - ${vcd_rde_interface.interface.id}
    name: MyType
    nss: nss
    schema: ${file("/home/foo/my_rde_type.json")}
    vendor: vendor
    version: 1.0.0

---

apiVersion: vcd.upbound.io/v1alpha1
kind: RdeTypeBehavior
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/rdetypebehavioracl
  labels:
    testing.upbound.io/example-name: behavior_override
  name: behavior-override
spec:
  forProvider:
    description: MyTypeBehaviorOverride
    execution:
      id: MyActivityOverride
      type: noop
    rdeInterfaceBehaviorId: ${vcd_rde_interface_behavior.behavior1.id}
    rdeTypeId: ${vcd_rde_type.type.id}
