apiVersion: vcd.upbound.io/v1alpha1
kind: RightsBundle
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/rightsbundle
  labels:
    testing.upbound.io/example-name: new-rights-bundle
  name: new-rights-bundle
spec:
  forProvider:
    description: new rights bundle from CLI
    name: new-rights-bundle
    publishToAllTenants: false
    rights:
    - 'Catalog: Add vApp from My Cloud'
    - 'Catalog: Edit Properties'
    - 'Catalog: View Private and Shared Catalogs'
    - 'Organization vDC Compute Policy: View'
    - 'vApp Template / Media: Edit'
    - 'vApp Template / Media: View'
    tenants:
    - org1
    - org2
