apiVersion: vcd.upbound.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/serviceaccount
  labels:
    testing.upbound.io/example-name: example_service
  name: example-service
spec:
  forProvider:
    active: true
    fileName: example_service.json
    name: example
    org: my-org
    role: ${data.vcd_role.vapp_author.id}
    softwareId: 12345678-1234-1234-1234-1234567890ab
    softwareVersion: 1.0.0
    uri: example.com
