apiVersion: vcd.upbound.io/v1alpha1
kind: SubscribedCatalog
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/subscribedcatalog
  labels:
    testing.upbound.io/example-name: subscriber
  name: subscriber
spec:
  forProvider:
    deleteForce: true
    deleteRecursive: true
    makeLocalCopy: true
    name: subscriber
    org: my-org
    subscriptionPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    subscriptionUrl: ${var.subscription_url}
