apiVersion: vcd.upbound.io/v1alpha1
kind: UiPlugin
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/uiplugin
  labels:
    testing.upbound.io/example-name: my_plugin
  name: my-plugin
spec:
  forProvider:
    enabled: true
    pluginPath: ./container-ui-plugin-4.0.zip
    tenantIds: ${data.vcd_org.my_plugin_orgs[*].id}
