apiVersion: vcd.upbound.io/v1alpha1
kind: VAppNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vappnetwork
  labels:
    testing.upbound.io/example-name: vappNet
  name: vappnet
spec:
  forProvider:
    dhcpPool:
    - endAddress: 192.168.2.50
      startAddress: 192.168.2.2
    dns1: 192.168.2.1
    dns2: 192.168.2.2
    dnsSuffix: mybiz.biz
    gateway: 192.168.2.1
    guestVlanAllowed: true
    name: my-net
    org: my-org
    prefixLength: "24"
    staticIpPool:
    - endAddress: 192.168.2.100
      startAddress: 192.168.2.51
    vappName: my-vapp
    vdc: my-vdc
