apiVersion: vcd.upbound.io/v1alpha1
kind: VAppFirewallRules
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vappfirewallrules
  labels:
    testing.upbound.io/example-name: vapp-fw
  name: vapp-fw
spec:
  forProvider:
    defaultAction: drop
    networkId: ${vcd_vapp_network.vapp-net.id}
    rule:
    - destinationIp: any
      destinationPort: "21"
      name: drop-ftp-out
      policy: drop
      protocol: tcp
      sourceIp: 10.10.0.0/24
      sourcePort: any
    - destinationIp: any
      destinationPort: any
      name: allow-outbound
      policy: allow
      protocol: any
      sourceIp: 10.10.0.0/24
      sourcePort: any
    vappId: ${vcd_vapp.web.id}

---

apiVersion: vcd.upbound.io/v1alpha1
kind: VApp
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vappfirewallrules
  labels:
    testing.upbound.io/example-name: web
  name: web
spec:
  forProvider:
    name: web

---

apiVersion: vcd.upbound.io/v1alpha1
kind: VAppNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vappfirewallrules
  labels:
    testing.upbound.io/example-name: vapp-net
  name: vapp-net
spec:
  forProvider:
    dns1: 192.168.2.1
    gateway: 192.168.2.1
    name: my-vapp-net
    netmask: 255.255.255.0
    orgNetworkName: my-vdc-int-net
    staticIpPool:
    - endAddress: 192.168.2.100
      startAddress: 192.168.2.51
    vappName: web
