apiVersion: vcd.upbound.io/v1alpha1
kind: VAppNatRules
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vappnatrules
  labels:
    testing.upbound.io/example-name: vapp-nat
  name: vapp-nat
spec:
  forProvider:
    enableIpMasquerade: false
    natType: portForwarding
    networkId: ${vcd_vapp_network.vapp-net.id}
    rule:
    - externalPort: "22"
      forwardToPort: "-1"
      protocol: TCP_UDP
      vmId: ${vcd_vapp_vm.vm1.id}
      vmNicId: "0"
    - externalPort: "-1"
      forwardToPort: "80"
      protocol: TCP
      vmId: ${vcd_vapp_vm.vm2.id}
      vmNicId: "0"
    vappId: ${vcd_vapp.web.id}

---

apiVersion: vcd.upbound.io/v1alpha1
kind: VApp
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vappnatrules
  labels:
    testing.upbound.io/example-name: web
  name: web
spec:
  forProvider:
    name: web

---

apiVersion: vcd.upbound.io/v1alpha1
kind: VAppFirewallRules
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vappnatrules
  labels:
    testing.upbound.io/example-name: vapp_fw1
  name: vapp-fw1
spec:
  forProvider:
    defaultAction: drop
    enabled: true
    networkId: ${vcd_vapp_network.vapp-net.id}
    vappId: ${vcd_vapp.web.id}

---

apiVersion: vcd.upbound.io/v1alpha1
kind: VAppFirewallRules
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vappnatrules
  labels:
    testing.upbound.io/example-name: vapp_fw2
  name: vapp-fw2
spec:
  forProvider:
    defaultAction: drop
    enabled: true
    networkId: ${vcd_vapp_network.vapp-org-net.id}
    vappId: ${vcd_vapp.web.id}

---

apiVersion: vcd.upbound.io/v1alpha1
kind: VAppNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vappnatrules
  labels:
    testing.upbound.io/example-name: vapp-net
  name: vapp-net
spec:
  forProvider:
    dns1: 192.168.2.1
    gateway: 192.168.2.1
    name: my-vapp-net
    netmask: 255.255.255.0
    orgNetworkName: my-vdc-int-net
    staticIpPool:
    - endAddress: 192.168.2.100
      startAddress: 192.168.2.51
    vappName: web

---

apiVersion: vcd.upbound.io/v1alpha1
kind: VAppOrgNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vappnatrules
  labels:
    testing.upbound.io/example-name: vapp-org-net
  name: vapp-org-net
spec:
  forProvider:
    isFenced: true
    orgNetworkName: ${vcd_network_routed.network-routed.name}
    vappName: web
