apiVersion: vcd.upbound.io/v1alpha1
kind: VAppOrgNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vapporgnetwork
  labels:
    testing.upbound.io/example-name: vappOrgNet
  name: vapporgnet
spec:
  forProvider:
    org: my-org
    orgNetworkName: my-org-network
    vappName: my-vapp
    vdc: my-vdc
