apiVersion: vcd.upbound.io/v1alpha1
kind: VApp
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vapp
  labels:
    testing.upbound.io/example-name: web
  name: web
spec:
  forProvider:
    metadataEntry:
    - key: CostAccount
      value: Marketing Department
    name: web

---

apiVersion: vcd.upbound.io/v1alpha1
kind: NetworkDirect
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vapp
  labels:
    testing.upbound.io/example-name: direct-network
  name: direct-network
spec:
  forProvider:
    externalNetwork: my-ext-net
    name: net

---

apiVersion: vcd.upbound.io/v1alpha1
kind: VAppOrgNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vapp
  labels:
    testing.upbound.io/example-name: direct-network
  name: direct-network
spec:
  forProvider:
    orgNetworkName: net
    vappName: web

---

apiVersion: vcd.upbound.io/v1alpha1
kind: VAppVm
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vapp
  labels:
    testing.upbound.io/example-name: web1
  name: web1
spec:
  forProvider:
    cpus: 1
    guestProperties:
      vapp.property1: value1
      vapp.property2: value2
    lease:
    - runtime_lease_in_sec: ${60 * 60 * 24 * 30}
      storage_lease_in_sec: ${60 * 60 * 24 * 7}
    memory: 2048
    name: web1
    network:
    - ipAllocationMode: POOL
      name: net
      type: org
    vappName: web
    vappTemplateId: ${data.vcd_catalog_vapp_template.photon-os.id}

---

apiVersion: vcd.upbound.io/v1alpha1
kind: VAppVm
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vapp
  labels:
    testing.upbound.io/example-name: web2
  name: web2
spec:
  forProvider:
    cpus: 1
    memory: 2048
    name: web2
    network:
    - ipAllocationMode: POOL
      name: net
      type: org
    vappName: web
    vappTemplateId: ${data.vcd_catalog_vapp_template.photon-os.id}
