apiVersion: vcd.upbound.io/v1alpha1
kind: VAppVm
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vappvm
  labels:
    testing.upbound.io/example-name: web1
  name: web1
spec:
  forProvider:
    cpuCores: 1
    cpus: 2
    guestProperties:
      another.var.name: var-value
      guest.hostname: my-host
    memory: 1024
    metadataEntry:
    - key: role
      value: web
    - key: env
      value: staging
    - key: version
      value: v1
    - key: my_key
      value: my value
    name: web1
    network:
    - ipAllocationMode: POOL
      isPrimary: true
      name: ${vcd_vapp_org_network.direct-net.org_network_name}
      type: org
    vappName: web
    vappTemplateId: ${data.vcd_catalog_vapp_template.photon-os.id}

---

apiVersion: vcd.upbound.io/v1alpha1
kind: IndependentDisk
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vappvm
  labels:
    testing.upbound.io/example-name: disk1
  name: disk1
spec:
  forProvider:
    busSubType: VirtualSCSI
    busType: SCSI
    name: logDisk
    size: "512"

---

apiVersion: vcd.upbound.io/v1alpha1
kind: NetworkDirect
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vappvm
  labels:
    testing.upbound.io/example-name: direct-external
  name: direct-external
spec:
  forProvider:
    externalNetwork: my-ext-net
    name: net

---

apiVersion: vcd.upbound.io/v1alpha1
kind: VApp
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vappvm
  labels:
    testing.upbound.io/example-name: web
  name: web
spec:
  forProvider:
    name: web

---

apiVersion: vcd.upbound.io/v1alpha1
kind: VAppNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vappvm
  labels:
    testing.upbound.io/example-name: vapp-net
  name: vapp-net
spec:
  forProvider:
    dns1: 192.168.2.1
    dns2: 192.168.2.2
    dnsSuffix: mybiz.biz
    gateway: 192.168.2.1
    guestVlanAllowed: true
    name: my-vapp-net
    netmask: 255.255.255.0
    staticIpPool:
    - endAddress: 192.168.2.100
      startAddress: 192.168.2.51
    vappName: web

---

apiVersion: vcd.upbound.io/v1alpha1
kind: VAppOrgNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vappvm
  labels:
    testing.upbound.io/example-name: direct-net
  name: direct-net
spec:
  forProvider:
    orgNetworkName: net
    vappName: web

---

apiVersion: vcd.upbound.io/v1alpha1
kind: VAppOrgNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vappvm
  labels:
    testing.upbound.io/example-name: routed-net
  name: routed-net
spec:
  forProvider:
    orgNetworkName: my-vdc-int-net
    vappName: web
