apiVersion: vcd.upbound.io/v1alpha1
kind: Vm
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vm
  labels:
    testing.upbound.io/example-name: TestVm
  name: testvm
spec:
  forProvider:
    cpus: 2
    memory: 2048
    name: TestVm
    network:
    - ipAllocationMode: POOL
      name: net-datacloud-r
      type: org
    vappTemplateId: ${data.vcd_catalog_vapp_template.photon-hw11.id}
