apiVersion: vcd.upbound.io/v1alpha1
kind: VmPlacementPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: vcd/v1alpha1/vmplacementpolicy
  labels:
    testing.upbound.io/example-name: test-placement-pol
  name: test-placement-pol
spec:
  forProvider:
    description: My awesome VM Placement Policy
    name: my-placement-pol
    providerVdcId: ${data.vcd_provider_vdc.pvdc.id}
    vmGroupIds:
    - ${data.vcd_vm_group.vm-group.id}
